const { env } = process;

module.exports = {
  type: 'object',
  properties: {
    port: { type: 'integer', default: env.PORT || 8080 },
    cors: { type: 'boolean', default: env.CORS || false },
    public: { type: 'string', default: env.PUBLIC },
    apiPrefix: { type: 'string', default: env.API_PREFIX || '/api' },
    databaseClient: { type: 'string', default: env.DATABASE_CLIENT || 'sqlite3' },
    databaseFile: { type: 'string', default: env.DATABASE_FILE || 'database.sqlite' },
    databaseUrl: { type: 'string', default: env.DATABASE_URL },
    databaseVersion: { type: 'string', default: env.DATABASE_VERSION },
    databaseSocketPath: { type: 'string', default: env.DATABASE_SOCKET_PATH },
    databaseHost: { type: 'string', default: env.DATABASE_HOST },
    databaseUser: { type: 'string', default: env.DATABASE_USER || env.USER },
    databasePassword: { type: 'string', default: env.DATABASE_PASSWORD },
    databaseName: { type: 'string', default: env.DATABASE_NAME },
    databaseDebug: { type: 'boolean', default: env.DATABASE_DEBUG },
    databaseDisabled: { type: 'boolean', default: env.DISABLE_DATABASE },
    databasePoolMin: { type: 'integer', default: env.DATABASE_POOL_MIN || 2 },
    databasePoolMax: { type: 'integer', default: env.DATABASE_POOL_MAX || 10 },
    webserverDisabled: { type: 'boolean', default: env.DISABLE_WEBSERVER },
    runSeeds: { type: 'boolean', default: false },
    runMigrateLatest: { type: 'boolean', default: false },
    runMigrateRollback: { type: 'boolean', default: false },
    shortLived: { type: 'boolean', default: false },
    modelPatterns: { type: 'array', default: ['**/*.model.js'] },
    routerPatterns: { type: 'array', default: ['**/*.router.js'] },
    actionPatterns: { type: 'array', default: ['**/*.action.js'] },
    seedPatterns: { type: 'array', default: ['**/*.seed.js'] },
    migrationPatterns: { type: 'array', default: ['**/*.migration.js'] },
    hookPatterns: { type: 'array', default: ['**/*.hook.js'] },
    ignorePatterns: { type: 'array', default: ['node_modules'] },
    models: { type: 'array' },
    routers: { type: 'array' },
    actions: { type: 'array' },
    seeds: { type: 'array' },
    migrations: { type: 'array' },
    hooks: { type: 'array' },
  },
};
